# Aplicar aproximaciones a para resolver transformadas de laplace de forma numerica

In [2]:
import numpy as np
from scipy.integrate import simps, trapz
from scipy.fftpack import ifft

Aproximacion de la transformada de laplace de la funcion f(t) utilizando el 
metodo de Simpson

In [3]:
def laplace_transform(func, t, s):
    F = np.zeros_like(s)
    for i, si in enumerate(s):
        integrand = lambda t: func(t) * np.exp(-si *  t)
        F[i] = simps(integrand(t), t)
    return F

Evaluacion para una funcion t**2

In [4]:
def func(t):
    return t**2

In [5]:
t = np.linspace(0, 10, 1000)
s = np.array([1 + 1j, 2 + 2j, 3 + 3j])

In [6]:
F = laplace_transform(func, t, s)
F

array([-0.49960854-0.50352725j, -0.06249989-0.06249993j,
       -0.01851844-0.01851852j])

In [12]:
def inverse_laplace(f, tmax, N):
    # Definir la malla de tiempo
    t = np.linspace(0, tmax, N)

    # Calcular la malla de frecuencia
    omega = 2 * np.pi * np.fft.fftfreq(N, tmax/N)

    # Calcular la malla de la transformada de laplace
    s = 1j * omega

    #Calcular la funcion F(s)
    Fs = f(s)

    #Calcular la integral de la transformada de laplace
    int_trapz = trapz(Fs * np.exp(s * t[:, np.newaxis]), s, axis = 1)
    int_simps = simps(Fs * np.exp(s * t[:, np.newaxis]), s, axis = 1)

    #Calcular la transformmada inversa de Fourier
    f_trapz = np.real(ifft(int_trapz))
    f_simps = np.real(ifft(int_simps))

    # Solucion

    return t, f_trapz, f_simps

In [8]:
def f(s):
    return 1/(s ** 2 + 1)

In [15]:
tmax = 1
N = 100

t, f_trapz, f_simps = inverse_laplace(f, tmax, N)

c:\Users\crist\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\integrate\_quadrature.py:507: ComplexWarning: Casting complex values to real discards the imaginary part
  h0 = np.float64(h[sl0])
c:\Users\crist\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\integrate\_quadrature.py:508: ComplexWarning: Casting complex values to real discards the imaginary part
  h1 = np.float64(h[sl1])


In [16]:
f_trapz

array([-4.70977424e-18, -2.66084052e-03, -2.60269081e-03, -1.72084153e-03,
       -1.28150055e-03, -1.01611217e-03, -8.37140949e-04, -7.07399270e-04,
       -6.08379186e-04, -5.29827835e-04, -4.65605499e-04, -4.11810644e-04,
       -3.65845004e-04, -3.25911102e-04, -2.90725507e-04, -2.59346928e-04,
       -2.31068821e-04, -2.05349896e-04, -1.81767751e-04, -1.59987095e-04,
       -1.39737435e-04, -1.20797050e-04, -1.02981225e-04, -8.61334320e-05,
       -7.01185497e-05, -5.48175253e-05, -4.01230235e-05, -2.59357449e-05,
       -1.21611540e-05,  1.29360154e-06,  1.45227857e-05,  2.76254004e-05,
        4.07089982e-05,  5.38943104e-05,  6.73211468e-05,  8.11562326e-05,
        9.56039940e-05,  1.10921888e-04,  1.27442879e-04,  1.45609473e-04,
        1.66027048e-04,  1.89550783e-04,  2.17433881e-04,  2.51594389e-04,
        2.95128391e-04,  3.53383193e-04,  4.36461351e-04,  5.66015019e-04,
        7.98325577e-04,  1.33944223e-03,  4.02869946e-03, -4.16620501e-03,
       -1.40104763e-03, -

In [17]:
f_simps

array([-1.25767452e-19, -1.29472983e-03, -6.10604683e-04,  2.92240952e-05,
        1.97537370e-05,  1.60371901e-05,  1.39759435e-05,  1.26456652e-05,
        1.17086021e-05,  1.10092590e-05,  1.04652960e-05,  1.00287644e-05,
        9.66974043e-06,  9.36853525e-06,  9.11164020e-06,  8.88946624e-06,
        8.69501168e-06,  8.52304058e-06,  8.36955655e-06,  8.23145472e-06,
        8.10628498e-06,  7.99208715e-06,  7.88727353e-06,  7.79054384e-06,
        7.70082243e-06,  7.61721127e-06,  7.53895431e-06,  7.46541003e-06,
        7.39603012e-06,  7.33034274e-06,  7.26793924e-06,  7.20846353e-06,
        7.15160349e-06,  7.09708397e-06,  7.04466110e-06,  6.99411754e-06,
        6.94525855e-06,  6.89790873e-06,  6.85190920e-06,  6.80711530e-06,
        6.76339457e-06,  6.72062499e-06,  6.67869355e-06,  6.63749489e-06,
        6.59693022e-06,  6.55690622e-06,  6.51733420e-06,  6.47812925e-06,
        6.43920945e-06,  6.40049524e-06,  6.36190868e-06,  6.32337288e-06,
        6.28481132e-06,  